---
title: "Revocación"
output: html_document
date: 2019-03-15
---

Luego de una tensa discusión donde Morena usó afiches de López Obrador y la oposición denunciaba que se aprobaba la antesala a la reelección de AMLO, la Cámara de Diputados aprobó las modificaciones constitucionales a los artículos 35, 36, 73, 81, 83, 99, 115 y 122 con la finalidad de flexibilizar las consultas populares y crear la figura de revocación de mandato. 

¿Qué plantea el polémico dictamen? En cuanto a las consultas populares reduce el porcentaje de firmas de ciudadanos requeridas para convocar la consulta del 2% al 1% de inscritos en la Lista Nominal. Agrega como materias que no se pueden consultar los tratados internacionales, bases y tasas impositivas, montos de financiamiento público y el presupuesto de egresos de la federación. En las modificaciones también se indica que la Suprema Corte de Justicia de la Nación deberá interpretar sobre la idoneidad de la pregunta de manera que sea favorable al derecho ciudadano y busca que las consultas se hagan el día que plantea su convocatoria y que ya no sean concurrentes con el proceso electoral federal. Para que el resultado de la consulta tenga efectos vinculantes, el dictamen reduce de 40% a 25% el porcentaje de participación de ciudadanos inscritos en la Lista Nominal. 

Esta minuta crea la figura de revocación de mandato y faculta al Congreso a legislar sobre la materia. La consulta para revocación de mandato podrá ser convocada por el Presidente, el 33% de los integrantes de la Cámara de Diputados o Senado, y por el 3% de las firmas de ciudadanos inscritos en la Lista Nominal. Los dos primeros casos deberán ser aprobados por mayoría en cada cámara. La parte *chistosa* del dictamen viene en las fracciones siguientes ya que plantea que la revocación de mandato en el primer periodo ordinario del segundo año de la legislatura (años 2 y 5 del sexenio) pero que la votación solo podrá realizarse de manera concurrente con las elecciones federales donde solo se renueve la Cámara de Diputados. La revocación será vinculante por mayoría absoluta siempre que participen al menos el 40% de los ciudadanos inscritos en la Lista Nominal. 

Esta reforma mandata al INE a organizar, recibir la votación y hacer los cómputos de la revocación de mandato y los resultados serán impugnables ante la Sala Superior del TEPJF quien declarará la validez. El Presidente revocado cesará su cargo al día siguiente y será sustituido de acuerdo al artículo 84 constitucional (no convocatoria a elecciones). Otro punto de la reforma establece que el objeto de la consulta de revocaciñon es que la ciudadanía decida **la permanencia del titular del Ejecutivo**, cosa que se presta a diversas interpretaciones, ya que luego del plazo fijo del cargo se utilice esto, junto con la contradicción de plazos antes mencionada, para que en lugar de elegir a un nuevo presidente, se ratifique la permanencia del ocupante.

A diferencia de la consulta para la presidencia, en el caso de revocación de mandato para gobernadores y jefe de gobierno de la Ciudad de México sí es clara la minuta, pues establece que la consulta deberá realizarse solo una vez en el periodo de gobierno y en caso de proceder, deberá efectuarse en el tercer año del periodo.

La minuta aprobada fue turnada al Senado. En mi opinión, espero que Morena y aliados (PT, PES, PVEM) no logren sumar la mayoría calificada para que no se apruebe esta figura que desvirtúa a mecanismos de participación ciudadana y constituye un falso mecanismo de rendición de cuentas vertical ya que el mismo Ejecutivo puede convocar a ella y puede convertirse en un cuidarse la espalda. En la lógica de la reelección consecutiva, un ocupante buscará seguir en su cargo en un siguiente periodo buscando aprobación de su *constituency* por su trabajo realizado, esto no ocurrirá con la revocación de mandato ya que se plantea a medio camino y tendrá un efecto de *presidential coattail* o arrastre al estar AMLO en campaña permanente con miras a superar la revocación y, como su partido es claramente de tipo personalista, empujar así a candidatos de Morena en la renovación de la Cámara de Diputados, gubernaturas, presidencias municipales y diputaciones locales aprovechando la concurrencia de procesos electorales federales y locales impuesta con la reforma político electoral de 2014. 