---
title: "Revivir al PES"
output: html_document
date: 2019-03-01
---

El Tribunal Electoral del Poder Judicial de la Federación (TEPJF) se prepara para cometer nuevamente una salvajada con el objetivo de otorgar el registro y prerrogativas al Partido Encuentro Social (PES), recordando la decisión de 2015 donde ordenó esperar los resultados de la elección extraordinaria en un distrito de Aguascalientes para que el Partido del Trabajo (PT) lograra superar el umbral y mantuviera su registro. 

Esta vez se trata de un proyecto elaborado por el Magistrado Felipe de la Mata donde se propone regresar el registro al PES y otorgarle prerrogativas al revocar un acuerdo del Instituto Nacional Electoral donde se confirmaba la pérdida de registro de este partido y de Nueva Alianza. 

El artículo 41 de la Constitución establece que para que un partido político nacional no se le cancele su registro, deberá obtener al menos 3% del total de la votación válida emitida en cualquiera de las elecciones presidencial, de diputaciones federales o de senadurías. Bajo este supuesto, el PES obtuvo 2.7% de los votos en la elección presidencial, 2.33% en la del Senado y 2.4% en la de la Cámara de Diputados, por lo que el INE decretó la pérdida del registro de este instituto político.

El proyecto del Magistrado de la Mata busca, a través de una regla que no existe en la ley llamada representación calificada, reviva este partido ya que llegaron bajo sus siglas 56 diputados y 8 senadores al Congreso. El sistema electoral es el conjunto de reglas que traducen los votos en escaños, pero este proyecto busca traducir escaños en votos ya que parte del supuesto de que el PES tiene 11.2% de representación en la Cámara de Diputados y el 6.25% en el Senado, cifras superiores al 3% de la votación válida emitida que es la que se usa para determinar si un partido accede al reparto de asientos por representación proporcional, tiempos en medios de comunicación y prerrogativas, así como conservar su registro nacional. 

El Magistrado de la Mata infiere también en una transferencia de votos de Morena hacia el PES o de nuevos votos inexistentes, ya que los 64 legisladores de mayoría relativa del PES llegaron gracias al convenio de coalición y a que los votantes tacharon el emblema del partido de AMLO impulsando así a legisladores que no son militantes de Morena. El convenio establecía que los legisladores integrarían los grupos parlamenarios según su partido de origen, el transguismo beneficiando a Morena ocurrió después. La Ley General de Instituciones y Procedimientos Electorales establece que los votos para un candidato de coalición se sumarán y contarán para cada uno de los partidos coaligados, también prohibe transferir o distribuir votación mediante el convenio de coalición; y que la suma distrital de votos a partidos coaligados se distribuirá de manera igual y se asignará la fracción restante a los partidos integrantes de la coalición con mayor votación, por lo que la interpretación de de la Mata resulta ilegal. 

Encuentro Social compitió en las elecciones de 2018 bajo una coalición parcial (al menos 50% de candidaturas son comunes) llamada Juntos Haremos Historia, postulando 292 fórmulas comunes para la Cámara de Diputados y 62 para el Senado. El PES tenía 75 candidatos propios para la cámara baja y 8 para el Senado, así como postular a AMLO para la elección presidencial. El detalle de la sobrerrepresentación del PES con muchos más legisladores que votos se debe a que competió en coalición con un partido cuyo candidato presidencial tenía un gran efecto de arrastre y los votantes tacharon el logotipo de Morena llevando al Congreso a candidatos del PES. 
