---
title: "100 días de destrucción"
output: html_document
date: '2019-03-10'
---

Sin duda, hay muchos problemas en México pero también hay muchas cosas que se habían estado haciendo bien. El ánimo de cambio de López Obrador tiene una capacidad de destrucción asombrosa que primero se antojaba describir como improvisación y curva de aprendizaje, pero ahora deja ver cierta perversión. En su discurso inaugural ante el Congreso de la Unión, AMLO culpó de todo problema a la política económica implementada en México desde 1982 describiendo a las décadas anteriores como un pasado glorioso que es inexistente, y no se da cuenta de que tales reformas se dieron a consecuencia de la crisis de deuda y borrachera petrolera de la *Docena trágica*.

En estos primeros 100 días de gobierno -que serían más si agregamos el periodo de transición donde Peña Nieto cedió todo espacio a AMLO- fuimos testigos de tres ejercicios de consulta popular que no han sido más que simulaciones y burla. Hechas por encima de la ley, seleccionando los lugares donde poner las casillas, sin Padrón Electoral ni cadena de custodia, y de decisiones ya tomadas de antemano pero buscando un respaldo popular a manera de justificación. Así se canceló la construcción del Nuevo Aeropuerto Internacional de México en el desecado Lago de Texcoco, se aprobó la creación de programas sociales que llama prioritarios y proyectos de infraestructura como la refinería de Dos Bocas en Tabasco y el Tren Maya, y que se terminaran las obras de un ducto para iniciar la operación de la termoeléctrica en Huexca, Morelos. 

También se dio una embestida contra los órganos constitucionales autónomos y reguladores que son parte importante del México de la transición democrática. Primero con las renuncias forzadas de integrantes de la Comisión Reguladora de Energía y de la Comisión Nacional de Hidrocarburos ante presiones de la Secretaria de Energía, Rocío Nahle, luego con recortes a su presupuesto y tabuladores de salarios que mermaron a la burocracia y afectaron a los servidores públicos de confianza -que son quienes hacen que las cosas funcionen- y dejando intocados a los sindicalizados que constituyen un lastre para las agencias del gobierno. Destacan algunas iniciativas como desaparición de los Organismos Públicos Locales Electorales y reducción de 11 a 7 consejeros del INE o las propuestas para renovar integrantes en la CRE y la SCJN de personajes con dudosas tablas para el puesto pero con probada lealtad con AMLO y Morena. A esto le sumo los ataques desde el púlpito mañanero a instituciones como el INAI y la contrarreforma educativa claudicando en favor del SNTE y la CNTE con la pretensión de desaparecer al órgano que genera datos y evaluación en materia educativa, el INEE.  

En estos 100 días también han ocurrido lamentables tragedias como la muerte de 5 personas en un accidente aéreo donde se encontraban la Gobernadora de Puebla Martha Érika Alonso y el Senador Rafael Moreno Valle, la explosión del ducto en Tlahuelilpan, Hidalgo con más de 130 muertes evitables de haber tomado medidas de protección civil y el asesinato del activista Samir Flores justo antes de la consulta de la termoeléctrica en Morelos a la que se oponía. 

En política exterior se optó por jugar otra vez al avestruz, leyendo solamente la primera mitad de la fracción X del 41 constitucional. De esta manera se simuló una neutralidad y llamado al diálogo entre Nicolás Maduro y el Presidente encargado de Venezuela, Juan Guaidó, separándose del apoyo expresado por el Grupo de Lima del que México todavía es parte. La presencia turística de México también se borró con la desaparición del Consejo de Promoción Turística de México y la atracción de inversión extranjera está en entredicho por el cierre de las agencias de ProMéxico. 

En política social se optó por desaparecer o alterar programas sociales y políticas públicas que gozaban de calificación aprobatoria como Oportunidades-Prospera o el financiamiento a estancias infantiles y refugios para mujeres víctimas de violencia, para dar paso a entregas directas de recursos a personas seleccionadas vía un censo hecho por gente del partido Morena donde recaban datos personales de los potenciales beneficiarios. La entrega directa de dinero abona a agradecer a AMLO por los recursos lo que deja ver el uso clientelar que dará a estos programas. Destaca el desfondar y criticar a las Organizaciones de la Sociedad Civil y a la prensa que señala los errores de este incipiente gobierno, como la persecución fiscal y críticas desde el púlpito al diario Reforma. 

Puedo sumar la negación de AMLO a siquiera hablar de derechos sexuales y reproductivos en el marco de la conmemoración del Día Internacional de la Mujer y los abucheos organizados por morenistas contra gobernadores de oposición que participaron en los actos de la campaña permanente que está haciendo por todo el país con pretexto de entregar apoyos a jóvenes, gente de la tercera edad, discapacitados y productores del campo a quienes les prometió distorsionantes precios de garantía y créditos a la palabra, creación de 100 universidades de las que se sospecha serán parecidas a la cuestionada UACM y el uso al contentillo de la historia de México.

No podemos perder de vista las reformas en materia político electoral que han anunciado como la reducción de presupuesto a los partidos políticos, ya que, junto con la operación por tierra, campaña permanente en giras y presencia en medios con miras a la cuestionada revocación de mandato, burlas a gobernadores de otros partidos, lealtades partidistas conseguidas y reducción de consejeros electorales, Morena podría reconstruir un proyecto similar al que tuvo el PRI antes de la apertura a la competencia electoral y condiciones equitativas en las elecciones. Tampoco podemos ignorar la descalifiación permanente de todo el que no está de acuerdo con él usando palabras que históricamente tienen connotación negativa como *conservadores* o *fifís*, o las agencias calificadoras de deuda que no compran su plan de rescate de PEMEX cuando deberíamos estar ya dentro de un plan de transición energética que se ha paralizado por la obsesión de AMLO por el petróleo y el carbón; así como el intento por tomar las instituciones con personas leales como ocurre con Banxico y la Corte.

En cuanto a la militarización del país no podemos cantar victoria. Se redujo el contenido militar de la iniciativa por la que se crea la Guardia Nacional pero podría encabezarla un militar en retiro o con licencia. Esta institución aún podría hacer las veces de ministerio público y quedó sin control parlamentario por lo que, sumada a la ampliación de delitos con prisión preventiva oficiosa, podría convertirse en un brazo ejecutor de las órdenes de quien ocupe la Presidencia de la República. 

No esperaba nada de AMLO, y aún así logró decepcionarme.



