---
title: "Reforma electoral"
output: html_document
date: 2019-06-26
---
<style>
body {
text-align: justify}
</style>

Después de un receso de 3 meses en los que terminé la tesis, regreso a escribir en este blog. 

En los foros que se llevaron a cabo en la Cámara de Diputados, legisladores, académicos, consejeros electorales y magistrados discutieron varias ideas sobre la reforma política en puerta. Las reformas políticas anteriores habían impulsado la apertura del sistema político (1963, 1977) o el fortalecimiento de las autoridades electorales creadas en 1990 (1996, 2007, 2014). Las reformas, desde 1990, eran impulsadas por los partidos que habían perdido las elecciones anteriores. Las iniciativas e ideas que se discuten en 2019 provienen del partido en el poder, un escenario inédito desde que tenemos democracia en México.

Morena, en voz del Diputrado Sergio Carlos Gutiérrez Luna, presentó una iniciativa que transformaría el andamiaje institucional en materia electoral con pretexto de la austeridad entendida de la forma en que Morena-AMLO la conciben. Dentro de sus propuestas hay cosas loables como sanciones para quienes cometan actos de violencia política en razón de género, pero también hay ideas que pueden resultar peligrosas porque apuntan a la centralización y control político del sistema electoral, así como debilitar a los partidos de oposición.  

Tenemos una democracia cara, construída con ladrillos de desconfianza frente a un entonces partido que lo controlaba todo. Las instituciones que hemos moldeado desde 1996 han hecho un buen trabajo y se han corregido varios defectos en la legislación electoral y en las prácticas, al grado de complicar cada vez más las cosas y añadir elementos de seguridad. Si queremos una democracia más barata, no debemos descuidar los principios rectores de nuestro sistema electoral como certeza, legalidad, independencia, imparcialidad, máxima publicidad y objetividad. Aumentar la austeridad como principio podría menoscabar la autonomía del INE. Con la idea de tener una democracia menos costosa se propuso reducir del 65% al 33% UMA en la fórmula del cálculo de prerrogativas de los partidos políticos, lo que dejaría en una ventaja relativa a Morena frente a los demás institutos políticos. ¿Por qué no revisar el doble financiamiento federal-estatal, o revisar la regla 70/30? 

De la misma forma, desaparecer a los OPLES y que sean absorbidos por los consejos locales del INE, llevaría a una sobrecarga de trabajo para la cual no se tienen las capacidades técnicas, de personal y presupuestarias. Se considera el supuesto erróneo de que los OPLES no cumplieron con su misión o que solamente trabajan en peridos electorales, cuando tienen actividades de capacitación y educación cívica a lo largo del año. Se corre peligro de que Morena y aliados controlen a estos nuevos consejos locales al ser nombrados por la mayoría calificada de la Cámara de Diputados quitando esta facultad al Consejo General del INE. Gutiérrez Luna también propuso que la fiscalización de partidos y candidatos se traslade a los nuevos consejos locales, retirando esta facultad que actualmente tiene el INE.

Por otro lado, el también Diputado de Morena, Pablo Gómez, promovió la idea de prescindir del Consejo General del INE por lo parciales o partidistas que pueden ser los consejeros. Si bien, es cierto que llegan patrocinados por un partido, no se puede conocer la identidad de quien los impulsó hasta que dejan el cargo y adquieren nuevas responsabilidades. 7 consejeros fueron nombrados en 2014, año en que Morena no existía y 4 en 2017, año en que la bancada de Morena apenas rebasaba los 30 diputados. Por decisiones recientes que involucran a Morena como el fideicomiso para la reconstrucción tras los sismos de septiembre de 2017, se presume de al menos un consejero alineado al partido en el poder, pero desaparecer al Consejo General rompería la cadena de confianza partidos-INE y la nueva Junta General Ejecutiva que propone Gómez sería nombrada por la mayoría calificada de Morena y aliados sin necesidad de negociar con algún partido de oposición. Gómez también pretende cerrar las 300 juntas distritales del INE, lo que complicaría la operación el día de la jornada electoral y quitar el Registro Federal de Electores al INE, una de las exigencias que el entonces PRD que él encabezaba logró.

Por parte del INE, los consejeros pidieron considerar qué cosas estaban bien para fortalecerlas, y qué cosas estaban mal para corregirlas. Deslizaron ideas como urna electrónica que abarataría el costo de la jornada electoral al prescindir de las boletas electorales y agilizaría la presentación de resultados, acabando con las dos instancias preliminares y los pesados cómputos. Esto tiene un problema, no hay internet en todo México y el sistema de la urna electrónica puede ser vulnerado a algún ataque, por lo que se tienen que tomar medidas de seguridad. 

¿Por qué no discutimos que tenemos un complejo sistema de impartición de justicia electoral que se dedica a enmendar la plana del INE ante reclamos de los partidos que buscan reducir sus sanciones? ¿Por qué no discutimos por cambiar el modelo de comunicación política que constituye una restricción a la libertad de expresión y a los actores no partidistas que buscan colocar los temas de su agenda? ¿Por qué no discutimos la existencia de la Sala Especializada del TEPJF que revisa a detalle los spots? ¿Por qué no se trata de controlar el dinero que fluye bajo la mesa el día de la jornada electoral y financiamiento irregular? 
¿Por qué no se discute el tener menos instancias de resultados preliminares, menos recuentos y tener eficiencia a la hora de dar resultados oficiales? ¿Por qué no se discuten los problemas de mujeres a quienes no se les permite ser candidatas o asumir el cargo para el que fueron electas, o aquellas personas que se hacen pasar como indígenas o trans cuando no lo son con tal de obtener una candidatura? Hay muchos asuntos importantes que están siendo ignorados por centrar el debate en la austeridad. 