---
title: "La justicia del espectáculo"
output: html_document
date: 2020-09-15
fontsize: 10pt
---
<style>
body {
text-align: justify}
</style>

En los últimos meses hemos sido testigos de 3 casos donde se pretende hacer justicia pero se tratan de meros espectáculos que logran distraernos de los problemas sanitarios y económicos causados por el gobierno y la pandemia por COVID-19.

**La consulta**

El proceso electoral 2020-2021, en el que se renovará la Cámara de Diputados, 15 gubernaturas y cientos de diputaciones locales, ya empezó y el Ejecutivo federal no puede hacer campaña y probablemente se verá obligado a limitar la difusión de sus conferencias diarias desde las cuales usa la estrategia de 'bully pulpit' para encontrar enemigos en su narrativa de nosotros-contra-ellos. El 'ellos' es esta vez los expresidentes en el periodo 1988-2018 y, según el discurso morenista, culpables de los males de México. 

En ese marco, Morena inició la infructuosa recolección de firmas (2% de la lista nominal) con el objetivo de convocar a una consulta popular para enjuiciar a los expresidentes por diversas acusaciones. Resulta que una vez que desocuparon Los Pinos, perdieron el fuero o inmunidad procesal, por lo que nada impide que la Fiscalía -autónoma solo de nombre- pudiera proceder con la investigación si es que hay delitos sobre ellos. El plazo de recolección de firmas vence hoy, por lo que el plan B fue enviar al Senado la solicitud para iniciar la consulta a través de un documento que inventa delitos inexistentes pero consignas acordes a la ideología del acusador tales como privatización de empresas paraestatales o el rescate de millones de ahorradores. Otras acusasiones como el supuesto fraude de 2006 son inexistentes y las relacionadas con el caso Lozoya aún están en el tintero. 

La consulta es preocupante por varios motivos: la pregunta resultará inconstitucional luego de que la revise la Corte, atenta contra la presunción de inocencia que toda persona goza antes de que se le prueben delitos, atenta contra la autonomía constitucional de la Fiscalía por ordenar qué hacer. Si la consulta procede, AMLO usará los meses previos al 1 de agosto para hacer campaña por el Sí, mismos meses en los que serán las campañas para las elecciones de junio 2020 y contaminará el proceso electoral. Si la consulta no procede por tratarse de un tema de derechos humanos, culpará al pleno de la Corte de no estar con el pueblo o de ser comparsa de los expresidentes y procederá a una consulta ilegal como las que ha hecho (NAIM, Morelos, Constellation Brands) y un juicio sumario. Ni la justicia ni los derechos humanos se consultan popularmente.


**Lozoya**

Otro caso con el que el ejecutivo ha lucrado desde su estrado mañanero es el proceso judicial al que es sujeto el exdirector de PEMEX en el sexenio anterior. Lozoya fue detenido en España y extraditado en México donde ha gozado de varios privilegios como hospedarse en el Hospital Ángeles del Pedregal a su llegada. Diversos delitos están en la fila del caso, desde recibir financiamiento ilícito para la campaña presidencial de 2012 hasta manejos sucios de las compras y actividades de la petrolera estatal. 

El espectáculo que AMLO ha montado desde Palacio Nacional transmitiendo desde ahí pruebas y videos, así como filtrar la declaración a los medios y redes sociales, pueden obstaculizar el proceso judicial de manera que será más difícil impartir justicia sobre uno de los artífices de la enorme corrupción que caracterizó al sexenio peñanietista. 

El tema Lozoya cayó en deshuso luego de que se revelara el financiamiento irregular de Morena previo a las elecciones de 2018, donde el gobierno de Chiapas a través de operadores del PVEM entregaran efectivo a la campaña amloista sin pasar por la fiscalización del INE y excedieran los montos permitidos. El pago de favores de Morena al Verde ha ido desde conceder licencia al senador Velasco para terminar su periodo de gobierno, convertirse en socio de las coaliciones legislativa y electoral, encabezar Protección Civil y un órgano nuevo que vigilaría la compra de medicamentos y presidir el Senado.


**El avión**

En medio de otra ridícula simulación disfrazada de justicia, hoy se llevará a cabo la supuesta rifa del avión presidencial. La aeronave arrendada que estuvo varios meses estacionada en California ha servido de pretexto para el discurso presidencial de austeridad y se opone a gastos onerosos en representación del pueblo pobre. Nos encontramos ante otro episodio demagógico que busca distraer nuestra atención de las más de 71 mil defunciones por COVID-19 y la crisis económica que atravesamos. 

Deshacerse del avión se ha vendido como un acto de justicia y como parte del discurso de austeridad enmarcado en el populismo de que no puede el representante 'único y genuino' del pueblo utilizarlo si el pueblo es pobre, pero probablemente el gasto por la renta del estacionamiento en California, el mantenimiento a la aeronave, los viajes de las comitivas y vuelos en naves de las fuerzas armadas que acompañan las giras, así como el monto ya pagado del arrendamiento superan lo que se podría recuperar con la eventual venta.

La contingencia por COVID-19 y el sorteo organizado por la Lotería Nacional crearon otra oportunidad para que continúe distrayendo a la opinión pública con el tema. Para el sorteo se imprimieron 6 millones de boletos con un precio de 500 cada uno, número y precio muchas veces superiores a los sorteos habituales, pero la trampa está en que se obligó 'voluntariamente' a cientos de burócratas a comprarlos y se utilizaron 500 millones de pesos recuperados por la Fiscalía para comprar un millón de boletos y entregarlos a los hospitales del sector salud en lugar de reintegrar el dinero a la hacienda pública y destinarlo a la contingencia sanitaria. El INSABI erogó más de 7 mil millones de pesos para entregar 51 mil boletos a los hospitales del sector público y, en caso de resultar ganadores, destinar el premio a equipo médico. 





