---
title: "Demócrata cuando me conviene"
output: html_document
date: 2020-09-06
---
<style>
body {
text-align: justify}
</style>

A unas horas de arrancar el proceso electoral 2020-2021, el INE se encontraba en medio de dos procesos que tendrán un impacto en las elecciones del próximo año: la renovación de la dirigencia nacional de Morena y el registro de nuevos partidos políticos. 

**Dirigencia nacional de Morena**

No es nuevo que el INE, antes IFE, participe en procesos de elección de dirigencias partidistas, pero su intervención se daba luego de que los partidos la pidieran y esta vez con Morena es distinto. Ante la incapacidad por parte del partido en el gobierno de organizar la renovación de su dirigencia, el Tribunal Electoral ordenó al INE llevar a cabo esta elección con cargo a las prerrogativas del partido y bajo la figura de una encuesta, de acuerdo a los estatutos del instituto político. Destacados morenistas acusan al Tribunal de injerencia en las actividades internas del partido, pero estos institutos políticos no son autónomos y deben seguir tanto la legislación electoral como sus obligaciones de transparencia entre las que se encuentra contar y publicar el padrón de militantes actualizado y ahí radica una de las complicaciones de este proceso. 

El INE es quien organiza las elecciones y no levanta encuestas ni cuenta con el personal para realizarlas. El INE tampoco tiene facultades para incidir en procesos internos de los partidos como la inscripción de militantes al padrón de los partidos. El INE sí está facultado a participar en la elección de dirigencias a petición de los partidos, pero ahora se trata de un mandato judicial ante la negación de la prórroga pedida por Morena y la incapacidad de este partido por conducir la renovación de la presidencia y secretaría general en los tiempos legales, aduciendo al inicio del proceso electoral y la conntingencia sanitaria. Esta situación llevó a demócratas cuando les conviene a acusar al Tribunal de realizar prácticas contrarias a la democracia y entrometerse en la vida interna del partido.

**Partidos no tan nuevos**

Durante la última sesión del Consejo General del INE, se discutió y votó por otorgar el registro a 7 asociaciones políticas que buscan figurar en la boleta de 2021 como partidos políticos. En la sesión destacó que todas las asociaciones cometieron diversas irregularidades en materias de fiscalización o de afrenta al carácter laico del estado en la forma de afiliación corporativa de personas sindicalizadas como militantes, aportaciones económicas irregulares, ministros de culto en calidad de dirigentes y militantes, afiliación de nuevos militantes en recintos religiosos entre otras. 

Todas las opciones políticas que se encontraban sobre la mesa son caras conocidas de la política mexicana y liderazgos caducos como la familia de la exlidereza del SNTE, Elba Esther Gordillo; la estructura sindical del SNTE que estuvo detrás de Nueva Alianza; Manuel Espino, exdirigente panista que hoy colabora con el gobierno de AMLO; Pedro Haces, senador suplente de Morena y líder sindical; expriistas como César Santiago y dos más que avanzaron en comisiones y generaron polémica por los motivos del debate: Encuentro Solidario, antes Social; y la organización encabezada por la excandidata independiente a la presidencia Margarita Zavala y el expresidente Felipe Calderón. Solamente el PES regresará, lamentablemente, a la boleta siendo un partido confesional una aberración dentro de un estado laico. 

La democracia no solo implica tener elecciones y una pluralidad de opciones para elegir, sino que quienes decidan participar conozcan, acepten y sigan las reglas. La laicidad se convirtió en uno de los pilares del estado mexicano desde mediados del siglo XIX, principio que se ve vulnerado al darle entrada a la boleta a partidos confesionales cuya ideología y propuestas de política pública giran alrededor de algún credo religioso. Esta situación ocurrió 2 veces, hace 6 años al aceptar a Encuentro Social y ahora como Encuentro Solidario donde consta la participación de ministros evangélicos bajo la figura de militantes y de dirigentes. El Consejo General votó 6-5 para regresar el registro a este partido, vulnerando a la Constitución. Las actividades político electorales no deben relacionarse con las actividades religiosas y gremiales.

Por otra parte, México Libre, que gira en torno a Zavala y Calderón, no logró acceder a la boleta de 2021 ya que el INE encontró que más del 8% de las aportaciones fueron recolectadas por unna forma que no permite la fiscalización adecuada al no transparenntar los datos de los aportantes, pero esta no fue la única irregularidad cometida por el partido de Zavala y Calderón, pues se detectó que afiliaron a más de mil militantes en templos católicos y sedes municipales.

Varias caras visibles de México Libre criticaron abiertamente a los consejeros Lorenzo Córdoba y Ciro Murayama acusando que, por no darles el registro, la democracia había muerto como si el régimen dependiera de la existencia o no de un partido más, encabezado por un liderazgo caduco al frente de la escisión un partido y cuyo antecedente electoral más próximo tuviera que suspender su campaña por la falta de fondos. 

Del otro lado del espectro, en Morena había quienes festejaban el no registro a ML aduciendo que si Zavala y Calderón hubieran obtenido el registro, la democracia mexicana habría muerto. Dos caras de la misma moneda de demócratas cuando les conviene. 

Analizando, ¿a quién le convenía que ML compitiera en 2021? A AMLO y Morena porque podría dividir el voto no-Morena-PT-PES-PVEM. ¿A quién le conviene que ML no obtuviera su registro? Al PAN, por ser el segundo partido en intención de voto para 2021 y ML ser una escición del PAN. ¿Podrá ML obtener el registro? Eso depende de cómo resuelva el TEPJF la impugnación. La principal razón es la imposibilidad de identificar y trasparentar los datos de quienes aportaron al partido zavalista-calderonista a través de Clip, plataforma que el CG del INE exhortó que se dejara de usar y que el partido en ciernes considera que cuentan con la forma de demostrar de dónde provienen tales fondos. 

La fiscalización de partidos políticos y candidaturas independientes es uno de los más grandes temas en los procesos electorales que se ha ido perfeccionando a través de las reformas electorales de los últimos 30 años. Recordando casos emblemáticos como Amigos de Fox y PEMEXgate en el año 2000, Monex en 2012 o el fideicomiso usado por Morena entre 2017 y 2019 covierten a las aportaciones irregulares de los protopartidos en uno de los puntos álgidos de cara a las elecciones del próximo año. 

