---
title: "Pasar la página y cerrar el capítulo"
output: html_document
date: 2020-08-03
---
<style>
body {
text-align: justify}
</style>

Después de meses sin escribir aquí, estoy de regreso y esta será una entrada muy personal. Han pasado meses muy locos para mí, sin considerar la pandemia, meses llenos de difíciles desiciones, encierro solitario y mucha introspección. Pero no todo es tan malo como suena, ya que al pasar esta página de mi vida me encuentro en algo mejor que lo que pudo ser y que, definitivamente, ya no será. 

Antes que nada, debo agradecer a todas las personas que me apoyaron cuando iba a iniciar esa etapa que hoy doy por cerrada: profesores, mis padres, mi hermano, y quien me invitó.  No es la primera vez que me encuentro en una situación en la que me siento mal profesional-vocacionalmente, pero luego de las veces anteriores y tomar terapias, sé que la forma para lograr dejar de sentirme mal es tomar una decisión que consista en dar vuelta a la página y cerrar el capítulo. 

Cuando te ofrecen una oportunidad en bandeja de plata, de algo que no deseabas pero no veías con malos ojos, sería un error no tomarla para al menos probar antes de descartar. Así ocurrió hace año y medio: solo tenía que aceptar una invitación para estar dentro de un programa doctoral en ciencia política, oportunidad que me deslumbró y animó, por lo que acepté. Primera vez que estaba yo por mi cuenta, en otro país y explorando para ver me agraaba y de qué se trataba la nueva experiencia.

De momento sí me impresioné y como dicen, que no haya ilusos para que no haya decepcionados, la desilusión llegó pero el barco ya había zarpado. No me gustó lo que se iba escribiendo en esa página y ya había empezado a reflejarse físicamente en mi salud. Luego de un semestre poco retador y releyendo literatura que conocí en la licenciatura llegó enero, mes donde el descontento ya comenzaba a cobrarme factura al estar muy distraído, no disfrutando lo que hacía, buscaba en qué distraerme mientras hacía como que atendía pero no sabía qué sería de mí ya que mis intereses no encajaban con la facultad ni compañeros porque no me llaman la atención la psicología social ni los conflictos armados internacionales, así como no me gustaba la forma en la que ahí desdeñaban la racionalidad. El panorama a corto y mediano plazo se antojaba desolador y la COVID-19 no era más que un suceso que estaba pasando aislado en China. 

En los últimos días de enero decidí dejar de pensar y actuar: comuniqué a quien me invitó mis inquietudes y mi decisión de abandonar el programa al terminar el semestre. Reconozco que me faltó tacto porque le cayó como una cubeta de agua fría, y quizá debí acudir a ayuda psicológica antes de iniciar la tormenta, pero ya no me podía callar. En las siguientes semanas las charlas para convencerme se empezaron a tornar personales y algo incómodas, al punto de saber que yo era parte de algo parecido a un plan diseñado que incluía incluso un par de distractores por aquello de no tan buenas prácticas. 

Unas semanas después inicié la terapia con el servicio de psicología que ofrecían al alumnado, asistí dos veces y tuve que dejar de recibir las consultas cuando se suspendieron las actividades presenciales por el inicio de la contingencia sanitaria por COVID-19. Al iniciar la suspensión de actividades me quedé solo y encerrado en el departamento por dos largos meses para acabar el semestre. Si no me regresé a mi casa de inmediato fue porque sabía que no atendería mis obligaciones hasta cerrar el semestre y lidiar con la soledad del encierro, el temor de contraer el virus, la preocupación por mi familia y las amenazas de cerrar fronteras con el miedo a quedarme varado y las pésimas decisiones de política pública por parte del gobierno del estado donde me encontraba. 

Sentía que no pertenecía, que era ajeno y que no me satisfacía lo que estaba haciendo. Varias personas me creían con un perfil que distaba mucho del mío y por ello esperaban ciertas cosas que nunca se habrían dado. Como es normal, me topé con la clásica persona que para desquitar su frustración con el mundo se la pasa tirando "verdades" para hacer sentir mal a todo mundo y, aunque fuera al margen, contribuyó a que me sientiera peor cuando ya estaba mal. 

El 5 de mayo se cumplen 3 meses de que regresé a México de manera definitiva. El doctor queda doblemente descartado y no pienso regresar a esos fríos lares. A futuro sí pensaría en estudiar un posgrado pero sería una maestría en algo más práctico y relacionado ya sea con lo que estoy haciendo o con mis intereses y me quedaría en México. Tuve la suerte de encontrar trabajo al mes de haber regresado, desde junio estoy con la Dirección de Estado Abierto, Estudios y Evaluación del Info CDMX, trabajando en temas de transparencia, acceso a la información y rendición de cuentas y aprendiendo mucho de un área que me interesaba pero era tangencial a lo que hacía. 

Desde que regresé a casa, los problemas de sueño se terminaron y con el encierro he podido pasar más tiempo de calidad con mi mamá, papá y mi hermano, a quienes extrañé mucho durante el año que estuve fuera. También he podido platicar más seguido y de manera virtual con amigos a quienes dejé de ver antes de partir y por teléfono a mi abuela a quien no he visto desde diciembre. 

No me arrepiento, al final queda un aprendizaje para saber que ese no era el camino por el cual seguir, conocí a mucha gente y viví experiencias nuevas con shock cultural de por medio. Cada persona es las decisiones que tomamos, tanto buenas como desafortunadas. Quizá algunas personas esperaban de mí cosas que no llegarían y afecté planes en los que me incluían pero era que yo ajeno a ellos, pero lo que importa es que yo esté y me sienta bien, y así me siento al pasar la página de este libro y cerrar este capítulo. 