---
title: "La política exterior del avestruz y la crisis venezolana"
output: html_document
date: 2019-01-05
---

El ganso se convirtió en avestruz cuando revivió al fantasma creado en 1930 por el ex canciller Genaro Estrada con la abstención del gobierno mexicano en la firma de la carta del Grupo de Lima donde 13 de 14 países miembros exhortan a Nicolás Maduro para que no tome posesión de la presidencia de Venezuela el 10 de enero en su segundo periodo para el cual resultó electo en unas cuestionadas e inequitativas elecciones que fueron manejadas por las instituciones paralelas que él mismo controla. 

Los venezolanos están sufriendo una crisis humanitaria sin precedentes en Latinoamérica, junto con altos niveles de violencia e hiperinflación. 

La carta acusa que las elecciones del 20 de mayo de 2018, convocadas por el Congreso Constituyente controlado por Maduro, no se dieron en condiciones democráticas (controladas por el gobierno madurista y prohibiendo a la oposición participar) y reconoce a la Asamblea Nacional (con mayoría opositora) y al Tribunal Supremo de Justicia (que opera en el exterior) como instituciones legítimamente conformadas de acuerdo a la Constitución venezolana vigente y acusan la ruptura del orden constitucional y el estado de derecho. 

México es parte del grupo de países que buscan restituir el orden democrático, imponer sanciones financieras a funcionarios bolivarianos y revisar las relaciones diplomáticas para impedir la entrada a los 14 países miembros de políticos del régimen maduristas.

El artículo 89 en su fracción X de la Constitución mexicana faculta al presidente a: 

  *"Dirigir la política exterior y celebrar tratados internacionales, así como terminar, denunciar, suspender, modificar, enmendar, retirar reservas y formular declaraciones interpretativas sobre los mismos, sometiéndolos a la aprobación del Senado. En la conducción de tal política, el titular del Poder Ejecutivo observará los siguientes principios normativos: la autodeterminación de los pueblos; la no intervención; la solución pacífica de controversias; la proscripción de la amenaza o el uso de la fuerza en las relaciones internacionales; la igualdad jurídica de los Estados; la cooperación internacional para el desarrollo; el respeto, la protección y promoción de los derechos humanos y la lucha por la paz y la seguridad internacionales."*

El nuevo gobierno de México justificó, en palabras de López Obrador, no firmar la carta por seguimiento de los principios constitucionales de no intervención y autodeterminación de los pueblos (principios de la llamada Doctrina Estrada), diciendo que el gobierno mexicano no se inmiscuirá en asuntos internos de otros países porque no quieren que otros gobiernos se entrometan en asuntos de México. Ambos principios citados en las declaraciones pueden leerse en la fracción arriba mencionada pero parece que AMLO ignora (selectivamente) los principios que se añadieron luego de la reforma constitucional en materia de derechos humanos de 2011. Esta reforma agregó al texto que la política exterior de México también se guiará por el respeto, protección y promoción de los derechos humanos y la lucha por la paz. 

Las violaciones a derechos humanos en Venezuela son evidentes y tienen sumidos en una crisis humanitaria y altos niveles de violencia a más de 31 millones de personas. Esta situación justifica que México forme parte del Grupo de Lima y que debía suscribir la carta firmada por los otros países miembros exigiendo la salida de Nicolás Maduro del gobierno bolivariano y entrega del poder para realizar nuevas elecciones como primeros pasos para restablecer el orden constitucional y estado de derecho. 

La forma de política exterior que está readoptando el gobierno mexicano surgió en el gobierno de Pascual Ortiz Rubio (1930-1932) como una forma de, al no criticar a otros gobiernos, buscar que no se criticara al gobierno mexicano. Esto no impidió que los gobiernos del priato criticaran la anexión de Austria por Alemania, a Pinochet y a Franco, mientras activamente reconocían y ayudaban al castrismo y al sandinismo. 

Cito la Doctrina Estrada: 

  *"El gobierno de México no otorga reconocimiento porque considera que esta práctica es denigrante, ya que a más de herir la soberanía de las otras naciones, coloca a éstas en el caso de que sus asuntos interiores pueden ser calificados en cualquier sentido por otros gobiernos, quienes, de hecho, asumen una actitud de crítica al decidir favorable o desfavorablemente sobre la capacidad legal de regímenes extranjeros. El gobierno mexicano sólo se limita a mantener o retirar, cuando lo crea procedente, a sus agentes diplomáticos, sin calificar precipitadamente, ni a posterior, el derecho de las naciones para aceptar, mantener o sustituir a sus gobiernos o autoridades."*
  
Retomando las palabras del subsecretario para América Latina, Maximiliano Reyes Zúñiga, México continuará los trabajos con el Grupo de Lima pero no firmó la carta diciendo que buscará una solución negociada. Con estas declaraciones, el gobierno de López Obrador está dando un espaldarazo al gobierno madurista. La solución negociada ya se intentó y no se llegó a nada ante la represión por parte de Maduro a los manifestantes en 2017 y la orden por parte del Tribunal Supremo de Justicia (controlado por el gobierno y nombrado de forma irregular en 2015) para que los partidos agrupados en la Mesa de Unidad Democrática no participaran en las elecciones de mayo de 2018 acusando que no cumplían el proceso de validación. 
