---
title: "Desabasto"
date: "6/1/2019"
output: html_document
---

Hace un par de semanas el gobierno federal anunció un plan para combatir el robo de combustibles (huachicol) incrementando la vigilancia a los ductos e instalaciones de PEMEX por elementos de las fuerzas armadas y, en un desplante de populismo penal, tipificar el robo de combustibles como un delito grave (algo ya no vigente con nuestro sistema penal acusatorio) que merece prisión preventiva oficiosa. 

En la primera semana del año se reportó escasez de gasolina en municipios de Michoacán y los días siguientes se sumaron reportes por desabasto en los estados de Jalisco, Querétaro, Tamaulipas, Guanajuato, Aguascalientes, Puebla, Estado de México, Hidalgo, Oaxaca, Nuevo León y Chihuahua. El gobierno de López Obrador reconoció que el desabasto fue provocado por la interrupción del bombeo de combustibles en los ductos que van a esos estados como parte de la estrategia contra el huachicoleo y usar pipas con la idea de disminuir el robo de gasolina por ordeña. 

Esta improvisada estrategia, al parecer, no tomó en cuenta las consecuencias de cortar el suministro de gasolina generaría desabasto al no considerar la capacidad de las Terminales de Abastecimiento y Reparto (TAR) a lo largo del sistema de ductos, principalmente el Sistema Sur-Centro-Golfo-Occidente que comunica 30 TAR ubicados en los estados más afectados como Jalisco, Michoacán, Guanajuato, Querétaro, Estado de México, Hidalgo y Puebla. Este sistema de ductos es el más afectado por puntos de ordeña. 

Según el reporte de tomas clandestinas 2018 de PEMEX, con información hasta octubre, los estados donde se han encontrado más puntos de ordeña son Puebla, 

Estado|Ene|	Feb|	Mar|	Abr|	May|	Jun|	Jul|	Ago|	Sep|	Oct|	Nov|	Dic|	Total
-|-|-|-|-|-|-|-|-|-|-|-|-|-
Ags|	0|0|	0|0|1|	0|0|1|0|0|-|-|2


2
BC	10
9	15	9	10	6
9
15
19
9	

111
BCS	0
0	0	0	0	0
0
0
0
0	

0
Camp	0
0	0	0	0	0
0
0
0
0	

0
Chis	0
1	0	1	0	1
3
3
6
2	

17
Chih	11
26	13	9	4	14
2
13
11
9	

112
Coah	5
1	0	1	4	7
4
1
4
1	

28
CDMX	6
25	30	13	2	2
3
1
0
1	

83
Col	0
0	0	0	0	0
0
0
0
0	

0
Dgo	1
2	6	0	1	2
8
1
2
2	

25
Gto	131
139	145	148	195	107
151
172
164
195	

1,547
Gro	0
0	0	0	0	0
0
0
0
0	

0
Hgo	139
143	173	151	163	140
146
201
235
235	

1,726
Jal	69
117	149	146	131	146
144
161
66
134	

1,263
Mex	98
113	104	103	172	141
119
148
142
128	

1,268
Mich	37
37	5	41	8	8
19
16
15
12	

198
Mor	51
41	49	67	0	0
0
0
0
0	

208
Nay	0
0	0	0	0	0
0
0
0
0	

0
NL	20
23	26	32	23	18
20
22
13
26	

223
Oax	15
9	9	8	15	6
18
15
18
22	

135
Pue	110
136	271	284	224	150
143
203
115
179	

1,815
Qro	26
21	25	42	28	19
34
27
18
35	

275
QR	0
0	0	0	0	0
0
0
0
0	

0
SLP	0
0	0	0	0	1
0
0
0
0	

1
Sin	95
109	48	36	34	23
23
17
17
10	

412
Son	6
11	10	17	28	21
20
12
18
24	

167
Tab	17	15	10	7	12	13
17
28
20
27	

166
Tamps	82	109	116	155	94	70
115
107
102
134	

1,084
Tlax	23	29	38	45	47	28
47
51
30
37	

375
Ver	94
112	175	170	157	136
107
144
124
119	

1,338
Yuc	0	0	0	0	1	1
0
0
0
0	

2
Zac	0	0	0	0	0	0
0
0
0
0	

0
	1,046	1,228	1,417	1,485	1,354	1,060
1,152
1,359
1,139
1,341	

12,581




